login:
    path: /login
    defaults: { _controller: BackendBundle:User:login}

login_check:
    path: /login_check

logout:
    path: /login

backend_admin_dashboard:
    path: /admin/dashboard
    defaults: { _controller: BackendBundle:Default:index}


#backend_homepage:
#    path:     /
#    defaults: { _controller: BackendBundle:Default:index }
  